import { describe, expect, test } from 'bun:test';
import { emit, parse } from './index';

/**
 * Regression guard for the "emit-only boilerplate clobber hole": getStaticPaths /
 * loadPageData / `const params = Astro.params` are covered UNCONDITIONALLY by the frontmatter
 * scanner but regenerated by emit ONLY for the matching page type (CMS template / SSR page).
 * A hand-authored page carrying one of these whose `meta` is NOT that type used to be treated
 * as editable and would SILENTLY DROP the construct on save (emit wouldn't regenerate it),
 * breaking the build. parseFile now flags such a mismatch as `unsupported` (read-only) so the
 * provider never re-emits it. See parseFile.detectOrphanedBoilerplate.
 */

const layout = (front: string, body = '<div>x</div>') =>
  `---\nimport { BaseLayout } from 'meno-astro/components';\n${front}\n---\n<BaseLayout meta={meta}>\n  ${body}\n</BaseLayout>\n`;

describe('orphaned emit-only boilerplate → read-only (not clobbered)', () => {
  test('getStaticPaths on a page whose meta is NOT a CMS template is read-only', () => {
    const src = layout(
      `export async function getStaticPaths() {\n  return [{ params: { id: '1' } }];\n}\n\nconst meta = { title: "Item" };`,
    );
    const { unsupported } = parse(src);
    expect(unsupported).toBeDefined();
    expect(unsupported?.reason).toContain('getStaticPaths');
  });

  test('loadPageData on a page whose meta is NOT an SSR page is read-only', () => {
    const src = layout(
      `import { loadPageData } from 'meno-astro';\n\nconst meta = { title: "Page" };\n\nconst { repo } = await loadPageData(meta.data, Astro);`,
    );
    const { unsupported } = parse(src);
    expect(unsupported).toBeDefined();
    expect(unsupported?.reason).toContain('loadPageData');
  });

  test('`const params = Astro.params` without an SSR dynamic route is read-only', () => {
    const src = layout(`const meta = { title: "Page" };\n\nconst params = Astro.params;`);
    const { unsupported } = parse(src);
    expect(unsupported).toBeDefined();
    expect(unsupported?.reason).toContain('Astro.params');
  });
});

describe('genuine dialect pages are NOT falsely flagged', () => {
  const cmsTemplate = {
    meta: {
      title: '{{cms.title}}',
      source: 'cms' as const,
      cms: {
        id: 'blog',
        slugField: 'slug',
        urlPattern: '/blog/{{slug}}',
        fields: { slug: { type: 'string' }, title: { type: 'string' } },
      },
    },
    root: { type: 'node' as const, tag: 'article', children: ['{{cms.title}}'] },
  };

  test('a real CMS template (source:cms + getStaticPaths) stays editable', () => {
    const { unsupported } = parse(emit(cmsTemplate as any));
    expect(unsupported).toBeUndefined();
  });

  test('a real SSR page (source:ssr + loadPageData) stays editable', () => {
    const ssr = {
      meta: {
        title: 'Live',
        source: 'ssr' as const,
        data: { sources: { repo: { type: 'fetch', url: 'https://x/y', fields: { name: 'string' } } } },
      },
      root: { type: 'node' as const, tag: 'div', children: ['{{repo.name}}'] },
    };
    const { unsupported } = parse(emit(ssr as any));
    expect(unsupported).toBeUndefined();
  });

  test('a real SSR dynamic route (routeParams + const params) stays editable', () => {
    const ssr = {
      meta: {
        title: 'Live',
        source: 'ssr' as const,
        routeParams: ['slug'],
        data: { sources: { repo: { type: 'fetch', url: 'https://x/{{params.slug}}', fields: { name: 'string' } } } },
      },
      root: { type: 'node' as const, tag: 'div', children: ['{{repo.name}}'] },
    };
    const out = emit(ssr as any);
    expect(out).toContain('const params = Astro.params;');
    expect(parse(out).unsupported).toBeUndefined();
  });

  test('the keyword inside a meta string is ignored (blankNonCode, no false positive)', () => {
    const src = layout(`const meta = { title: "function getStaticPaths() in Astro" };`);
    expect(parse(src).unsupported).toBeUndefined();
  });
});
